### ISSUE TITLE
Error while freezing minified css

### ISSUE THREAD

**Issue by jifeon** [bem/borschik#94]
During freezing
```css
.icon-service-attraction-inactive{background:url(../img/sprites/services.png)}.icon-service-attraction-white-md{background:url(../img/sprites/services.png)}
```
borschik fails
```
Error: No such file or directory: /Volumes/Workspace/projects/datravel-website/application/public/freezing/public/img/sprites/services.png)}.icon-service-attraction-white-md{background:url(../img/sprites/services.png
  -> /Volumes/Workspace/projects/datravel-website/application/public/freezing/public/css/common_bottom.min.css
    at exports.Tech.base.Tech.inherit.File.exports.File.base.File.inherit.processLink [as __base] (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/techs/css-base.js:54:27)
    at exports.Tech.base.Tech.inherit.File.exports.File.base.File.inherit.processLink (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/techs/css.js:104:68)
    at null.processLink (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/node_modules/inherit/lib/inherit.js:81:36)
    at exports.Tech.INHERIT.File.exports.File.INHERIT.process (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/tech.js:138:54)
    at exports.Tech.base.Tech.inherit.File.exports.File.base.File.inherit.processInclude (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/techs/css.js:97:61)
    at exports.Tech.INHERIT.File.exports.File.INHERIT.process (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/tech.js:138:26)
    at exports.Tech.INHERIT.process (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/tech.js:34:56)
    at Cmd.<anonymous> (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/coa.js:137:38)
    at /Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/node_modules/coa/lib/cmd.js:483:22
    at _fulfilled (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/node_modules/coa/node_modules/q/q.js:798:54)
```
Note the file name:
```
services.png)}.icon-service-attraction-white-md{background:url(../img/sprites/services.png
```
All works well if I freeze the file with line breaks:
```css
.icon-service-attraction-inactive {
    background: url(../img/sprites/services.png)
}
.icon-service-attraction-white-md {
    background: url(../img/sprites/services.png)
}
```
